version: '3.8'
services:
  mqtt:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    volumes:
      - "/opt/mosquitto-data:/mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    network_mode: host
    command: "mosquitto -c /mosquitto-no-auth.conf"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt
    volumes:
      - /opt/zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    network_mode: host
    environment:
      - TZ=Europe/Prague
    devices:
      - /dev/ttyACM0:/dev/ttyACM0

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /opt/HA:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    network_mode: host
    environment:
      TZ: 'Europe/Prague'
      WEBPASSWORD: 'root'
      DNSMASQ_USER: 'root'
      ServerIP: "192.168.1.5"
      QUERY_LOGGING: "false"
    volumes:
      - '/opt/pihole/:/etc/pihole/'
      - '/opt/pihole/dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
